before_script:
- pip install tox

pypy27:
  image: pypy:2.7
  script: tox -e pypy

pypy36:
  image: pypy:3.6
  script: tox -e pypy3

python27:
  image: python:2.7
  script: tox -e py27

python35:
  image: python:3.5
  script: tox -e py35

python36:
  image: python:3.6
  script: tox -e py36

python37:
  image: python:3.7
  script: tox -e py37
